from enum import Enum


class Marks(str, Enum):
    ACURA = 'Acura'
    ALFA_ROMEO = 'Alfa Romeo'
    ASTON_MARTIN = 'Aston Martin'
    AUDI = 'Audi'
    BENTLEY = 'Bentley'
    BMW = 'BMW'
    BUICK = 'Buick'
    BUGATTI = 'Bugatti'
    CADILLAC = 'Cadillac'
    CHEVROLET = 'Chevrolet'
    FERRARI = 'Ferrari'
    FIAT = 'Fiat'
    FORD = 'Ford'
    GMC = 'GMC'
    HONDA = 'Honda'
    HYUNDAI = 'Hyundai'
    INFINITI = 'Infiniti'
    JAGUAR = 'Jaguar'
    JEEP = 'Jeep'
    KIA = 'Kia'
    LAMBORGHINI = 'Lamborghini'
    LAND_ROVER = 'Land Rover'
    LEXUS = 'Lexus'
    LINCOLN = 'Lincoln'
    MASERATI = 'Maserati'
    MAZDA = 'Mazda'
    MERCEDES_BENZ = 'Mercedes-Benz'
    MINI = 'Mini'
    MITSUBISHI = 'Mitsubishi'
    NISSAN = 'Nissan'
    PORSCHE = 'Porsche'
    RAM = 'Ram'
    ROLLS_ROYCE = 'Rolls-Royce'
    SMART = 'Smart'
    SUBARU = 'Subaru'
    TESLA = 'Tesla'
    TOYOTA = 'Toyota'
    VOLKSWAGEN = 'Volkswagen'
    VOLVO = 'Volvo'
